### ISSUE TITLE
problem saving big decimal

### ISSUE THREAD

**Issue by AndreLZGava** [maurcarvalho/jquery_mask_rails#1]
Hello I'm using this gem for my application and i'm using for validate money in R$ but when I try to save on database rails convert value (received in model as string to decimal) but that find last first . and convet something like "10.000.000,00" to 10.00 how shoud I use this? ou is there a way to remove mask on submit form?

**Comment by areanto** [comment]
Did you solve it?

im using this, but it cant accept separator ,00

```
$(".money").mask('000.000.000.000', { reverse: true });

$('#name_of_your_button').click(function () {
$('.money').unmask();
})
```

**Comment by AndreLZGava** [comment]
I did in rails, receive as string convert and clean mask, then worked :)

**Comment by areanto** [comment]
right, i see you are using regex to clean it. thx
